version: "3.0"

services:
  main:
    container_name: main
    build:
      context: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:4000
    command: npm run start:docker
    restart: always
